---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 811288377093.dkr.ecr.us-west-2.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
